/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AutoRolling from "./scripts/AutoRolling"
import BridCtrl from "./scripts/BridCtrl"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/AutoRolling.js",AutoRolling);
		reg("scripts/BridCtrl.js",BridCtrl);
    }
}
GameConfig.width = 2048;
GameConfig.height = 1024;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "game_scene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
