/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AutoRolling from "./scripts/AutoRolling"
import BridCtrl from "./scripts/BridCtrl"
import CloumnCreate from "./scripts/CloumnCreate"
import UiCtrl from "./scripts/UiCtrl"
import cloumn from "./scripts/cloumn"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/AutoRolling.js",AutoRolling);
		reg("scripts/BridCtrl.js",BridCtrl);
		reg("scripts/CloumnCreate.js",CloumnCreate);
		reg("scripts/UiCtrl.js",UiCtrl);
		reg("scripts/cloumn.js",cloumn);
    }
}
GameConfig.width = 2048;
GameConfig.height = 1024;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "game_scene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
