/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import startPanel from "./startPanel"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("startPanel.js",startPanel);
    }
}
GameConfig.width = 1080;
GameConfig.height = 1920;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "mainScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
